// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQIDI3SiK5pJjDKJMo5L4zL_D3NKgesY',
    appId: '1:957128503993:web:5f57fb78b684f4b4aea168',
    messagingSenderId: '957128503993',
    projectId: 'ufapp-bb146',
    authDomain: 'ufapp-bb146.firebaseapp.com',
    storageBucket: 'ufapp-bb146.firebasestorage.app',
    measurementId: 'G-VEXTXFEN3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Dq1ORJq2rSHL9TvxCDq1HFJSmfNiXxw',
    appId: '1:957128503993:android:7194b211d96f9b3aaea168',
    messagingSenderId: '957128503993',
    projectId: 'ufapp-bb146',
    storageBucket: 'ufapp-bb146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSbMH51gO7TfKDUyIgATVQ-GF4p9_tLs',
    appId: '1:957128503993:ios:024050590c7f1f70aea168',
    messagingSenderId: '957128503993',
    projectId: 'ufapp-bb146',
    storageBucket: 'ufapp-bb146.firebasestorage.app',
    iosBundleId: 'com.example.uffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSbMH51gO7TfKDUyIgATVQ-GF4p9_tLs',
    appId: '1:957128503993:ios:024050590c7f1f70aea168',
    messagingSenderId: '957128503993',
    projectId: 'ufapp-bb146',
    storageBucket: 'ufapp-bb146.firebasestorage.app',
    iosBundleId: 'com.example.uffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQIDI3SiK5pJjDKJMo5L4zL_D3NKgesY',
    appId: '1:957128503993:web:561ba4f7c3f64297aea168',
    messagingSenderId: '957128503993',
    projectId: 'ufapp-bb146',
    authDomain: 'ufapp-bb146.firebaseapp.com',
    storageBucket: 'ufapp-bb146.firebasestorage.app',
    measurementId: 'G-ENS8GGK1F3',
  );
}
